project:
  type: website
  output-dir: docs

website:
  title: "Yasmin Lukman - PSCI 3200"   
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: rq_data.qmd
        text: Research Question
         - href: rq_data2.qmd
        text: Research Question 2