project:
  type: website
  output-dir: docs

website:
  title: "Yasmin Lukman - PSCI 3200"   
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: rq_data.qmd
        text: Research Question
      - href: rq_data2.qmd
        text: Research Question 2
      - href: rq_data3.qmd
        text: Research Question 3
execute:
  echo: false
  warning: false
  message: false
  
bibliography: references.bib
