<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yasmin Lukman">
<meta name="dcterms.date" content="2026-05-10">

<title>Economic Hardship, Environmental Concern,and Public Support for Galamsey in Ghana – Yasmin Lukman - PSCI 3200</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-1d4f84655f446305ac42a8f1abcf7405.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Yasmin Lukman - PSCI 3200</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./rq_data3.html" aria-current="page"> 
<span class="menu-text">Final Project</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-more" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">More</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-more">    
        <li>
    <a class="dropdown-item" href="./rq_data.html">
 <span class="dropdown-text">Preliminary Research Design</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./rq_data2.html">
 <span class="dropdown-text">Expanded Research Design</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Economic Hardship, Environmental Concern,and Public Support for Galamsey in Ghana</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Yasmin Lukman </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Pennsylvania
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 10, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>A well-documented finding in environmental sociology and economics is that concern for the environment tends to rise with income <span class="citation" data-cites="fairbrother2012">(<a href="#ref-fairbrother2012" role="doc-biblioref">Fairbrother 2012</a>)</span>. Wealthier individuals, and wealthier nations, express greater willingness to prioritize ecological protection over economic growth. Yet this pattern may reflect the insulation that prosperity affords, rather than genuine environmental virtue. Wealthy nations, heavily populated within the Global North, have largely externalized the costs of their economic growth, through historical emissions, resource extractions, and industrial production, onto the populations least equipped to absorb them, mostly categorized by the Global South. Communities across sub-Saharan Africa, South and Southeast Asia, and Latin America face the sharpest consequences of global environmental degradation, despite having contributed a smaller fraction of cumulative greenhouse gas emissions. Thus, while the economies of the Global North create the atmospheric conditions driving climate change, “the Global South bears the brunt of its devastation” <span class="citation" data-cites="tougas2021global">(<a href="#ref-tougas2021global" role="doc-biblioref">Tougas and Arshad-Ayaz 2021</a>)</span>. For these populations, environmental concern is not an abstract policy preference but a lived condition, and in contexts of acute hardship people may face a sharper trade-off between survival and environmental protection. This relationship then raises a more difficult question: when individuals face a direct and immediate trade-off between livelihood and environmental harm, does environmental concern contract in favor of a greater economic well-being? How individuals resolve that trade-off and the factors that shape their resolution remains under explored in the empirical literature on environmental attitudes in developing contexts.</p>
<p><span class="citation" data-cites="Franzen2010">Franzen and Meyer (<a href="#ref-Franzen2010" role="doc-biblioref">2009</a>)</span>, in their paper on Environmental Attitudes in Cross-National Perspective, claim that “individuals who live in a relatively high-income household, as measured by the deviation from a country’s mean income, report a higher concern for the environment than individuals in households with relatively lower income.” Franzen and Meyer also deduce from their findings that this individual effect confirms the “prosperity assumption” which states that one’s willingness to invest in the quality of an environment increases with income, and that a concern for the environment depends on individuals’ post materialistic attitudes, which include fighting for environmental protection. This post materialist thesis suggests that environmental concern is a luxury afforded by economic security. Where basic needs remain unmet, individuals and communities are more likely to prioritize immediate survival over long-term ecological considerations, out of rational necessity.</p>
<p>Researchers have also observed that environmental concern is not uniform, and varies significantly by country, income level, and degree of economic vulnerability. This comes from inquiry on how populations in developing contexts weigh environmental risk against immediate livelihood pressures. In the paper, The Impact of Macroeconomic Factors on Environmental Concern, <span class="citation" data-cites="conroy2014">Conroy and Emerson (<a href="#ref-conroy2014" role="doc-biblioref">2014</a>)</span>, find that in general, when economic conditions are “unfavorable”, like higher unemployment, or lower GDP growth in an economy, respondents are more likely to believe that, at least in the case of the U.S, the government is “spending too much on ‘improving and protecting the environment’”. This follows their notion that environmental quality is a normal pro-cyclical good and that environmental spending (or the concern related to its spending) should rise when an economy is expanding and fall during economic contractions.</p>
<p>This paper examines how acute economic hardships shape environmental values among individuals whose livelihoods depend on environmentally destructive activity, using Ghana’s illegal small-scale mining sector- known locally as galamsey- as the empirical setting. Galamsey has contaminated over 60% of the country’s water sources with heavy metals, yet it persists because it provides livelihoods for hundreds of thousands of Ghanaians with few economic alternatives. A paper on the health hazards associated with the exposure to galamsey-related pollutants shows how galamsey, although a lucrative source of income for some underprivileged areas, comes with pollutants that “contaminate water bodies and ecosystems with high concentrations of mercury, acid, arsenic, lead and nickel” and “the release of toxic petroleum hydrocarbons(like methane and volatile organic carbons) due to spills and leaks,” which “poses significant risks to ecosystems and human health.” <span class="citation" data-cites="awewomom2024">(<a href="#ref-awewomom2024" role="doc-biblioref">Awewomom et al. 2024</a>)</span>. These risks with environmental and health concerns may seem enough to deter the practice. However, existing research shows that illegal mining in Ghana is shaped by both economic necessity and environmental concern. A study that examined the gaps between mining laws and galamsey’s persistence highlighted that the act provides livelihoods for many while causing environmental damage. The study also notes that economic pressures like unemployment push participation.<span class="citation" data-cites="vovobu2024">(<a href="#ref-vovobu2024" role="doc-biblioref">Vovobu 2024</a>)</span></p>
<p>While the economic dimensions of illegal mining are well-documented, the environmental attitudes of those involved remain comparatively under-explored. This has significant implications for understanding participation in illegal mining in developing contexts like Ghana, where high unemployment and limited economic alternatives constrain the range of priorities people can hold.</p>
<p>My research question then, to find out if there are any trade-offs between care for the environment and economic well-being, is:</p>
<p><strong>To what extent do economic hardship and environmental concerns influence attitudes toward illegal mining in Ghana?</strong></p>
<p>Understanding this matters because it may explain why the act persists despite its damaging effects. If support for illegal mining is driven by poverty rather than indifference to environmental harm, then criminalizing the act without addressing its economic roots may not change public behavior. This conjunction of environmental harm, acute economic need and direct livelihood dependence makes galamsey a sharp case for studying how the trade-off between survival and environmental protection may be resolved in practice.</p>
</section>
<section id="hypothesis" class="level1">
<h1>Hypothesis</h1>
<p><strong>Individuals experiencing greater economic hardship will be more likely to express supportive or tolerant attitudes toward illegal mining in Ghana, even when they recognize its environmental harms.</strong></p>
<p>This hypothesis rests on the theoretical logic that economic necessity restructures how individuals prioritize competing goods, and how they evaluate environmentally harmful activities. When basic material needs like food, shelter or income, are unmet , people are less likely to prioritize longer-term goods like environmental protection.</p>
<p>Maslow’s Hierarchy of Needs provides a useful framework here: physiological and safety needs occupy the base of the hierarchy and must be satisfied before individuals attend to higher-order concerns. Environmental protection sits outside of these foundational tiers. The key theoretical implication is that economic hardship shifts the trade-off calculation, tolerating environmental damage becomes a rational response when the alternative is a deprivation of basic needs.</p>
<p>In the Ghanaian context of illegal mining, this persists partly because it provides an important short term source of income for individuals for limited employment opportunities. The lack of alternative jobs pushes many people, especially those who have lost agricultural income, to turn to mining as a means of survival. When survival depends on daily revenue, the environmental costs of mining like contaminated waterways and mercury exposure, may be recognized but de-prioritized. This is the core mechanism linking economic hardship to tolerant attitudes toward illegal mining, that necessity weakens the weight individuals assign to environmental harm in their evaluative calculus.</p>
<p>Conversely, those with greater economic security , measured by having a stable, formal employment or diversified income sources, will have less favorable attitudes toward illegal mining in Ghana. Without the dependence on mining income, they bear the environmental costs of galamsey without receiving its economic benefits. For these individuals, opposition to illegal mining is both economically rational and environmentally motivated. The visibility of environmental damage, such as contaminated water or mercury-related deaths, may reinforce negative attitudes particularly among those not materially compensated by the activity.</p>
</section>
<section id="data-and-research-design" class="level1">
<h1>Data And Research Design</h1>
<p>This study draws on Afrobarometer Round 7 conducted in Ghana in 2017 by the research organization, <span class="citation" data-cites="afrobarometer_r7">Afrobarometer (<a href="#ref-afrobarometer_r7" role="doc-biblioref">2018</a>)</span> . The unit of analysis is the individual respondent and the sample contains approximately 2,400 Ghanaian citizens above the age of 18.&nbsp;</p>
<p>The specific variables I used to test my hypothesis were Galamsey Support, Q83a, as the dependent variable, measured by the survey question asking whether citizens should be able to engage in illegal small-scale mining(1) or should not engage in it for any reason (2). Responses are coded on a five-point scale ranging from 1 (agree strongly with 1) to 5(agree with neither), with 4 (agree strongly with 2) being disapproval of galamsey for any reason.</p>
<p>The primary independent variable is Lived Poverty Index(LPI), a composite measure constructed by averaging five survey items that ask respondents how often, over the past year, they went without: (1) food, (2) clean water, (3) medical care, (4) cooking fuel, and (5) a cash income. Each item is coded on a five-point scale from 0(never) to 4(always). These five items are then averaged to produce a continuous index ranging from 0 to 4, where higher scores reflect greater material deprivation.</p>
<p>Taking this average is appropriate because it treats each domain of hardship as equally weighted and captures a generalized experience of poverty rather than deprivation in any single area. Respondents with missing values on one or more of the five items were excluded form the index calculation to ensure that the average accurately reflects responses across all dimensions rather than being skewed by partial data.</p>
<p>The secondary independent variable is Environmental Concern, measured using Q76 in the Afrobarometer survey, which asks respondents whether climate change needs to be stopped and how much ordinary citizens can do to stop this climate change as a serious issue requiring public action and collective responsibility. Environmental Concern is defined here as an individual’s perceived deterioration of environmental conditions based on direct, lived experience and the need for change to be made. While no question in the Round 7 instrument directly asks about environmental concern or galamsey-specific environment degradation, this proxy is theoretically defensible in the Ghanaian context because support for climate action reflects a broader awareness of environmental threats and the importance of environmental protection. Given Galamsey’s well-documented destruction of water bodies, farmland, and forest cover respondents who believe ordinary citizens must act against climate change are more plausibly environmentally conscious overall. This relationship is especially relevant in Ghana, where illegal mining activity act as a “threat to agricultural lands” and lead to “deforestation leading to soil erosion, destruction of agricultural lands and pollution of water bodies.” <span class="citation" data-cites="gyimah2019">(<a href="#ref-gyimah2019" role="doc-biblioref">Gyimah 2019</a>)</span>, posing danger to both environmental sustainability and rural livelihoods.</p>
<p>Environmental Concern in this case is coded from 0 (no, climate change does not need to be stopped) to 3 (yes, climate change needs to be stopped and ordinary citizens can do a lot). This means a value of 3 reflects greater perceived environmental deterioration and collective action to ameliorate climate change.</p>
<section id="descriptive-statistics" class="level3">
<h3 class="anchored" data-anchor-id="descriptive-statistics">Descriptive Statistics</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>               Variable Mean Min  Max   SD
1      Galamsey Support 3.36 1.0 5.00 1.06
2   Lived Poverty Index 1.35 0.5 3.83 0.42
3 Environmental Concern 1.73 0.0 3.00 1.11</code></pre>
</div>
</div>
<p>Figure 1 presents the descriptive statistics for the three key variable. Galamsey Support with a mean of of 3.36 on a 1-5 scale, suggesting on average, respondents lean modestly away from approval of illegal mining. The Lived Poverty Index has a mean of 1.35 on a 0-4 scale, reflecting that the average respondent experiences moderate poverty but not severe material deprivation. Environmental Concern has a mean of 1.73 and suggests that respondents recognize some need for climate change to be stopped and that ordinary citizens can do something about it.</p>
<p>To test whether economic hardship and environmental concern pull in opposite directions and whether poverty conditions the weight individuals place on environmental concern when evaluating galamsey, the main specification is an OLS regression model.</p>
<p><span class="math display">\[
\begin{aligned}
\text{GalamseySupport}_i &amp;= \beta_0 + \beta_1 \text{Poverty}_i + \beta_2 \text{EnvConcern}_i \\
&amp;\quad + \beta_3 (\text{Poverty}_i \times \text{EnvConcern}_i) \\
&amp;\quad + \beta_4 \text{WaterSatisfaction}_i + \beta_5 \text{Urban}_i + \beta_6 \text{Employment}_i \\
&amp;\quad + \beta_7 \text{Education}_i + \beta_8 \text{Region}_i + \beta_9 \text{PartyID}_i + \epsilon_i
\end{aligned}
\]</span></p>
</section>
<section id="key-coefficients" class="level2">
<h2 class="anchored" data-anchor-id="key-coefficients">Key Coefficients</h2>
<p>β1 captures the baseline relationship between economic hardship and galamsey support, holding all other variables constant. The hypothesis would predict β1 &gt;0, meaning higher poverty is associated with greater support for galamsey.</p>
<p>β2 looks at if environmental concern reduces support for galamsey, where β2 &lt; 0. This would mean greater environmental concern should generally be associated with lower support for galamsey, as individuals who have higher environmental concern are less likely to tolerate the ecological damage it produces.</p>
<p>β3 is the interaction term between environmental concern and poverty index. This tests the conditional hypothesis directly, whether economic hardship weakens the negative relationship between environmental concern and galamsey support. The expectation is β3 &gt; 0. Among respondents experiencing greater poverty, environmental concern may be less predictive of opposition to galamsey, because the trade-off between survival environmental protection that underlies the theoretical framework is only observable with this interaction. A positive β3 indicates that as poverty increases, the dampening effect of environmental concern on galamsey support weakens. This is also consistent with the Maslow-based logic developed in the hypothesis section.</p>
</section>
<section id="control-variables" class="level2">
<h2 class="anchored" data-anchor-id="control-variables">Control Variables</h2>
<p>β4- Water Satisfaction: Individuals who are dissatisfied with the government’s provision of water and sanitation services may be more likely to oppose galamsey if they attribute poor water access to illegal mining’s contamination of local waterways. Without controlling for this, the effect of environmental concern could be confounded by a direct, personal experience of environmental harm, outside of galamsey, like living in an area with prior industrial pollution or poor sanitation practices.</p>
<p>β5- Urban/Rural Context: Urban and rural respondents differ systematically in their proximity to mining activity, their dependence on natural resources and their exposure to galamsey’s harms and benefits. Rural individuals, particularly in mining regions, may be more economically reliant or directly affected by illegal mining. Omitting this could risk confounding geographic exposure with economic hardship.</p>
<p>β6- Employment Status: Employment captures a dimension of economic vulnerability from the poverty index. A respondent may score moderately on a poverty index but be acutely vulnerable due to unemployment. Including employment alongside poverty prevents the poverty coefficient from absorbing employment-driven variation.</p>
<p>β7- Education: This is associated with both environmental awareness and economic status, making it a potential confounder in both directions. The more educated an individual is, the stronger their environmental values, independent of income may be. They may also be more economically secure. Without controlling for education, it may be difficult to isolate whether observed attitude differences reflect economic hardship or differential environmental literacy.</p>
<p>β8- Region: Ghana’s regions vary in their exposure to illegal mining, proximity to affected ecosystems and historical relationship with mining. Respondents in the Ashanti or Western Regions, where illegal mining is most concentrated, may hold systematically different attitudes than those in the North. Region also correlates with poverty levels, as some regions may be poorer than others, making it an important control.</p>
<p>β9-PartyID: Party identification correlates with political affiliation in Ghana that may shape attitudes toward state enforcement of environmental regulations and economic development priorities. Since both major parties, NPP and NDC, have taken varying positions on galamsey crackdowns, party ID could confound the relationship between economic hardship and attitudes if it correlates with both.</p>
<p>ϵi​ is the error term, capturing at unobserved terms in galamsey attitudes not accounted for by the model. Relevant omitted variables may include social norms within mining communities, which may not be easily captured in standard survey instruments.</p>
</section>
<section id="threats-and-confounders" class="level2">
<h2 class="anchored" data-anchor-id="threats-and-confounders">Threats and Confounders</h2>
<p>A key threat in interpreting the coefficient in economic hardship as causal is omitted variable bias. Unobserved factors such as local employment opportunities and trust in the government may influence both individuals’ economic conditions and their attitudes toward illegal mining. These can be potential confounders that confuse the relationship. Reverse causality is also a concern, as individuals who support or participate in illegal mining may experience different economic outcomes as a result.</p>
</section>
</section>
<section id="findings" class="level1">
<h1>Findings</h1>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="rq_data3_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Figure 2: A grouped bar chart showing support for illegal mining (galamsey) across levels of lived poverty. A higher score on the galamsey support variable indicates disapproval or indifference of illegal small-scale mining.(Afrobarometer Round 7 Ghana Survey)</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure 2 displays the distribution of Galamsey Support across levels of Lived Poverty. First, the majority of respondents fall within the moderate poverty category, with comparatively few reporting very high levels of deprivation. Across all poverty levels, responses are heavily concentrated on “Agree strongly with 2”, that is strong agreement that citizens should not engage in galamsey under any circumstances, suggesting that unconditional disapproval is the dominant view regardless of poverty experience. If the hypothesis holds, that higher lived poverty is associated with greater support for galamsey, then one would expect to see a relative increase in agreement with statement 1 as poverty levels rise. However, this plot offers limited support for this pattern: in the moderate poverty group, agreement with both statements 1 and 2 is visible, whereas in the high and very high poverty groups, the bars for statement 1 are negligibly small. This runs counter to the hypothesis, as those experiencing greater deprivation do not appear more likely to endorse galamsey participation.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="rq_data3_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Figure 3: A grouped bar chart showing support for illegal mining (galamsey) and environmental concern. A higher score on the galamsey support variable indicates greater approval of illegal small-scale mining.(Afrobarometer Round 7 Ghana Survey)</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure 3 reveals that across all levels of galamsey attitudes, the dominant response is strong agreement with statement 2 (value 4, that citizens should not engage in galamsey for any reason), with this category containing the largest number of respondents. This pattern holds across all four environmental concern groups, suggesting that unconditional disapproval of galamsey is widespread regardless of how concerned respondents are about the environment. If the hypothesis holds, one would expect respondents with higher environmental concern to cluster more heavily at values 3 and 4 on the x-axis. The graph offers modest support for this, with answers “Yes, climate change needs to be stopped and citizens can do a little to stop climate change” and “Yes, climate change needs to be stopped and citizens can do a lot to stop climate change” being the largest groups at value 4 on Support for Galamsey while the other two answers remain consistently smaller across all categories. However, this pattern is difficult to interpret as a clear relationship because virtually all environmental concern groups peak at value 4.</p>
<section id="regression-results" class="level2">
<h2 class="anchored" data-anchor-id="regression-results">Regression Results</h2>
<div class="cell">
<div class="cell-output-display">
<!-- preamble start -->

    <script src="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js"></script>

    <script>
      // Create table-specific functions using external factory
      const tableFns_46cl1wbk90z4bmyk0hr8 = TinyTable.createTableFunctions("tinytable_46cl1wbk90z4bmyk0hr8");
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: '11', j: 2 } ], css_id: 'tinytable_css_mymykjr3vk48dn5co310',}, 
          { positions: [ { i: '8', j: 2 } ], css_id: 'tinytable_css_gjxctd8eps51x3iys71u',}, 
          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 } ], css_id: 'tinytable_css_0slokziok6qtx6b6r7uh',}, 
          { positions: [ { i: '0', j: 2 } ], css_id: 'tinytable_css_58ekfz6m7z8omb3fkgum',}, 
          { positions: [ { i: '11', j: 1 } ], css_id: 'tinytable_css_a8g7vymqw8acgtfnxeo9',}, 
          { positions: [ { i: '8', j: 1 } ], css_id: 'tinytable_css_9zgozoh6a2jy3haegzny',}, 
          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 } ], css_id: 'tinytable_css_kqem747v4ol5qa4rlkl0',}, 
          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_61c8i0fzixygtcasiyky',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  tableFns_46cl1wbk90z4bmyk0hr8.styleCell(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css">
    <style>
    /* tinytable css entries after */
    #tinytable_46cl1wbk90z4bmyk0hr8 td.tinytable_css_mymykjr3vk48dn5co310, #tinytable_46cl1wbk90z4bmyk0hr8 th.tinytable_css_mymykjr3vk48dn5co310 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_46cl1wbk90z4bmyk0hr8 td.tinytable_css_gjxctd8eps51x3iys71u, #tinytable_46cl1wbk90z4bmyk0hr8 th.tinytable_css_gjxctd8eps51x3iys71u {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_46cl1wbk90z4bmyk0hr8 td.tinytable_css_0slokziok6qtx6b6r7uh, #tinytable_46cl1wbk90z4bmyk0hr8 th.tinytable_css_0slokziok6qtx6b6r7uh { text-align: center }
    #tinytable_46cl1wbk90z4bmyk0hr8 td.tinytable_css_58ekfz6m7z8omb3fkgum, #tinytable_46cl1wbk90z4bmyk0hr8 th.tinytable_css_58ekfz6m7z8omb3fkgum {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_46cl1wbk90z4bmyk0hr8 td.tinytable_css_a8g7vymqw8acgtfnxeo9, #tinytable_46cl1wbk90z4bmyk0hr8 th.tinytable_css_a8g7vymqw8acgtfnxeo9 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_46cl1wbk90z4bmyk0hr8 td.tinytable_css_9zgozoh6a2jy3haegzny, #tinytable_46cl1wbk90z4bmyk0hr8 th.tinytable_css_9zgozoh6a2jy3haegzny {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_46cl1wbk90z4bmyk0hr8 td.tinytable_css_kqem747v4ol5qa4rlkl0, #tinytable_46cl1wbk90z4bmyk0hr8 th.tinytable_css_kqem747v4ol5qa4rlkl0 { text-align: left }
    #tinytable_46cl1wbk90z4bmyk0hr8 td.tinytable_css_61c8i0fzixygtcasiyky, #tinytable_46cl1wbk90z4bmyk0hr8 th.tinytable_css_61c8i0fzixygtcasiyky {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    </style>
    <div class="container">
      <table class="tinytable" id="tinytable_46cl1wbk90z4bmyk0hr8" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        <caption>Regression Model: Predictors of Support for Illegal Mining (Galamsey)</caption>
        <thead>
              <tr>
                <th scope="col" data-row="0" data-col="1"> </th>
                <th scope="col" data-row="0" data-col="2">(1)</th>
              </tr>
        </thead>
        <tfoot><tr><td colspan="2">* p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td></tr>
<tr><td colspan="2">Standard errors in parentheses.</td></tr>
<tr><td colspan="2">Factor controls included for water satisfaction, urban/rural, employment, region,education and party ID.</td></tr>
<tr><td colspan="2">Data: Afrobarometer Round 7 Ghana Survey</td></tr></tfoot>
        <tbody>
                <tr>
                  <td data-row="1" data-col="1">Intercept</td>
                  <td data-row="1" data-col="2">1.962**</td>
                </tr>
                <tr>
                  <td data-row="2" data-col="1"></td>
                  <td data-row="2" data-col="2">(0.639)</td>
                </tr>
                <tr>
                  <td data-row="3" data-col="1">Lived Poverty Index</td>
                  <td data-row="3" data-col="2">0.092</td>
                </tr>
                <tr>
                  <td data-row="4" data-col="1"></td>
                  <td data-row="4" data-col="2">(0.190)</td>
                </tr>
                <tr>
                  <td data-row="5" data-col="1">Environmental Concern</td>
                  <td data-row="5" data-col="2">0.161</td>
                </tr>
                <tr>
                  <td data-row="6" data-col="1"></td>
                  <td data-row="6" data-col="2">(0.131)</td>
                </tr>
                <tr>
                  <td data-row="7" data-col="1">Poverty × Environmental Concern (Interaction)</td>
                  <td data-row="7" data-col="2">-0.104</td>
                </tr>
                <tr>
                  <td data-row="8" data-col="1"></td>
                  <td data-row="8" data-col="2">(0.093)</td>
                </tr>
                <tr>
                  <td data-row="9" data-col="1">Num.Obs.</td>
                  <td data-row="9" data-col="2">663</td>
                </tr>
                <tr>
                  <td data-row="10" data-col="1">R2</td>
                  <td data-row="10" data-col="2">0.139</td>
                </tr>
                <tr>
                  <td data-row="11" data-col="1">R2 Adj.</td>
                  <td data-row="11" data-col="2">0.095</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
<p>Figure 4: Regression of Galamsey Support on Lived Poverty Index, Environmental Concern and Their Interaction</p>
</div>
</div>
<p>The regression model predicting support for illegal mining (galamsey) does not support the hypothesis that individuals experiencing greater economic hardship will be more likely to express supportive or tolerant attitudes toward illegal mining in Ghana, even when they recognize its environmental harms. The Lived Poverty Index carries a coefficient of 0.092 (SE=0.190), indicating that a one-unit increase in experienced poverty is associated with only a 0.092-point increase in galamsey support, which is a substantive negative effect that is consistent with the economic survival hypothesis, which would predict poorer individuals to be more supportive of illegal mining as a livelihood strategy. This is, however, far too small to be considered meaningful. Environmental Concern similarly carries a positive coefficient of 0.161(SE=0.0131), that runs counter to theoretical expectations. This shows greater environmental concern is associated with marginally more support for galamsey, rather than less, but this is also too small to be considered meaningful on its own. The interaction term between poverty and environmental concern is negative, implying that among poorer respondents, environmental concern slightly dampens galamsey support , though the effect of -0.104 is negligible in magnitude.</p>
<p>Overall, the findings do not provide statistical evidence for the economic survival argument. Although the direction of the poverty coefficient is consistent with the hypothesis, its size is weak and the lack of significance means the result could be due to chance. With 663 observations, the model has a reasonably large sample size but the explanatory power has some variation as R2 = 0.139 and adjusted R2 is 0.095. This suggests that the model explains only a limited share of the variation in support for galamsey, and that other factors not included may be likely important in shaping attitudes.</p>
</section>
</section>
<section id="empirical-extension" class="level1">
<h1>Empirical Extension</h1>
<p>Although my original hypothesis expected economic hardship to increase support for illegal mining as a means of survival, the empirical findings reveal a null result, meaning poverty does not significantly predict galamsey support in either direction (0.092, SE= 0.190, p&gt;0.05). However, the null raises a more nuanced possibility that the effect of poverty on galamsey attitudes may not operate uniformly across population, but instead varies depending on individual’s degree of direct exposure to galamsey’s environmental harms. If environmental vulnerability is the mechanism linking hardship to galamsey opposition, then poverty should predict less galamsey support most strongly among those most directly exposed to illegal mining’s consequences, namely rural residents, while having little to no effect among urban respondents.</p>
<p>To test this, I will test an interaction between Lived Poverty Index and Urban/Rural Status, asking whether the relationship between poverty and galamsey support differs systematically across geographic contexts. A negative interaction would mean that poverty reduces galamsey support, specifically among those most exposed to its environmental consequences.</p>
<p>The OLS regression model is thus:</p>
<p><span class="math display">\[ \begin{aligned} \text{GalamseySupport}_i &amp;= \beta_0 + \beta_1 \text{Poverty}_i + \beta_2 \text{Urban}_i \\ &amp;\quad + \beta_3 (\text{Poverty}_i \times \text{Urban}_i) \\ &amp;\quad + \beta_4 \text{WaterSatisfaction}_i + \beta_5 \text{EnvConcern}_i + \beta_6 \text{Employment}_i \\ &amp;\quad + \beta_7 \text{Education}_i + \beta_8 \text{Region}_i + \beta_9 \text{PartyID}_i + \epsilon_i \end{aligned} \]</span></p>
<div class="cell">
<div class="cell-output-display">
<!-- preamble start -->

    <script src="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js"></script>

    <script>
      // Create table-specific functions using external factory
      const tableFns_c4gk2dwubkm93kbe2nng = TinyTable.createTableFunctions("tinytable_c4gk2dwubkm93kbe2nng");
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: '13', j: 2 } ], css_id: 'tinytable_css_xtyxkqsaxr9ntqpnykxz',}, 
          { positions: [ { i: '10', j: 2 } ], css_id: 'tinytable_css_eqq3luscql42aw8q9wgc',}, 
          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 } ], css_id: 'tinytable_css_kn32uvsgkv2beucquhbe',}, 
          { positions: [ { i: '0', j: 2 } ], css_id: 'tinytable_css_tyj0bxtuljg2rgvduscc',}, 
          { positions: [ { i: '13', j: 1 } ], css_id: 'tinytable_css_2cbes5udb52ekjgs3juh',}, 
          { positions: [ { i: '10', j: 1 } ], css_id: 'tinytable_css_c2ancxn516l41467wb49',}, 
          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 } ], css_id: 'tinytable_css_rsb90khheehgcxzbe5s9',}, 
          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_eix8bfvsa3omz89hdt98',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  tableFns_c4gk2dwubkm93kbe2nng.styleCell(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css">
    <style>
    /* tinytable css entries after */
    #tinytable_c4gk2dwubkm93kbe2nng td.tinytable_css_xtyxkqsaxr9ntqpnykxz, #tinytable_c4gk2dwubkm93kbe2nng th.tinytable_css_xtyxkqsaxr9ntqpnykxz {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_c4gk2dwubkm93kbe2nng td.tinytable_css_eqq3luscql42aw8q9wgc, #tinytable_c4gk2dwubkm93kbe2nng th.tinytable_css_eqq3luscql42aw8q9wgc {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_c4gk2dwubkm93kbe2nng td.tinytable_css_kn32uvsgkv2beucquhbe, #tinytable_c4gk2dwubkm93kbe2nng th.tinytable_css_kn32uvsgkv2beucquhbe { text-align: center }
    #tinytable_c4gk2dwubkm93kbe2nng td.tinytable_css_tyj0bxtuljg2rgvduscc, #tinytable_c4gk2dwubkm93kbe2nng th.tinytable_css_tyj0bxtuljg2rgvduscc {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_c4gk2dwubkm93kbe2nng td.tinytable_css_2cbes5udb52ekjgs3juh, #tinytable_c4gk2dwubkm93kbe2nng th.tinytable_css_2cbes5udb52ekjgs3juh {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_c4gk2dwubkm93kbe2nng td.tinytable_css_c2ancxn516l41467wb49, #tinytable_c4gk2dwubkm93kbe2nng th.tinytable_css_c2ancxn516l41467wb49 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_c4gk2dwubkm93kbe2nng td.tinytable_css_rsb90khheehgcxzbe5s9, #tinytable_c4gk2dwubkm93kbe2nng th.tinytable_css_rsb90khheehgcxzbe5s9 { text-align: left }
    #tinytable_c4gk2dwubkm93kbe2nng td.tinytable_css_eix8bfvsa3omz89hdt98, #tinytable_c4gk2dwubkm93kbe2nng th.tinytable_css_eix8bfvsa3omz89hdt98 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    </style>
    <div class="container">
      <table class="tinytable" id="tinytable_c4gk2dwubkm93kbe2nng" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        <caption>Regression Model: Heterogenous Effects of Poverty on Galamsey Support by Urban/Rural Status</caption>
        <thead>
              <tr>
                <th scope="col" data-row="0" data-col="1"> </th>
                <th scope="col" data-row="0" data-col="2">(1)</th>
              </tr>
        </thead>
        <tfoot><tr><td colspan="2">* p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td></tr>
<tr><td colspan="2">Standard errors in parentheses.</td></tr>
<tr><td colspan="2">Factor controls included for water satisfaction, employment,region,education and party ID.</td></tr>
<tr><td colspan="2">Data: Afrobarometer Round 7 Ghana Survey</td></tr></tfoot>
        <tbody>
                <tr>
                  <td data-row="1" data-col="1">Intercept</td>
                  <td data-row="1" data-col="2">2.007***</td>
                </tr>
                <tr>
                  <td data-row="2" data-col="1"></td>
                  <td data-row="2" data-col="2">(0.607)</td>
                </tr>
                <tr>
                  <td data-row="3" data-col="1">Lived Poverty Index</td>
                  <td data-row="3" data-col="2">-0.101</td>
                </tr>
                <tr>
                  <td data-row="4" data-col="1"></td>
                  <td data-row="4" data-col="2">(0.146)</td>
                </tr>
                <tr>
                  <td data-row="5" data-col="1">Rural</td>
                  <td data-row="5" data-col="2">-0.113</td>
                </tr>
                <tr>
                  <td data-row="6" data-col="1"></td>
                  <td data-row="6" data-col="2">(0.279)</td>
                </tr>
                <tr>
                  <td data-row="7" data-col="1">Environmental Concern</td>
                  <td data-row="7" data-col="2">0.025</td>
                </tr>
                <tr>
                  <td data-row="8" data-col="1"></td>
                  <td data-row="8" data-col="2">(0.039)</td>
                </tr>
                <tr>
                  <td data-row="9" data-col="1">Poverty × Rural (Interaction)</td>
                  <td data-row="9" data-col="2">0.054</td>
                </tr>
                <tr>
                  <td data-row="10" data-col="1"></td>
                  <td data-row="10" data-col="2">(0.197)</td>
                </tr>
                <tr>
                  <td data-row="11" data-col="1">Num.Obs.</td>
                  <td data-row="11" data-col="2">663</td>
                </tr>
                <tr>
                  <td data-row="12" data-col="1">R2</td>
                  <td data-row="12" data-col="2">0.121</td>
                </tr>
                <tr>
                  <td data-row="13" data-col="1">R2 Adj.</td>
                  <td data-row="13" data-col="2">0.090</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
<p>Figure 5: Regression of Galamsey Support on Lived Poverty Index, Urban/Rural and Their Interaction</p>
</div>
</div>
<p>Lived Poverty Index is not significant from the model’s results. This represents the effect of poverty on galamsey support among urban respondents specifically. The negative direction suggests that urban poor are marginally less supportive of galamsey, but the effect is tiny and statistically indistinguishable from zero. Urban poverty does not, therefore, predict galamsey attitudes. With Rural being -0.113 as well shows that rural respondents are less supportive than urban respondents on average, but the effect is small as well. Thus, where one lives alone does not predict galamsey support. The poverty and rural interaction is insignificant as well. This means that poverty does not predict galamsey support differently in rural versus urban areas.</p>
<p>Overall, like the main model showing that poverty has no average effect on galamsey support, the placebo model shows this null result is not masked by opposing effects across rural and urban population. Even among rural respondents who are most directly exposed to galamsey’s environmental harms through polluted water sources, poverty does not translate into stronger opposition to illegal mining.</p>
</section>
<section id="discussion-and-policy-implications" class="level1">
<h1>Discussion and Policy Implications</h1>
<p>This study set out to examine whether economic hardship increases support for illegal small-scale mining (galamsey) in Ghana, hypothesizing that individuals experiencing greater poverty would be more tolerant of galamsey as an informal livelihood strategy. The empirical evidence does not support this hypothesis. Across the main regression model and the empirical extension, the Lived Poverty Index consistently fails to reach statistical significance, with magnitudes too small to be considered meaningful. Crucially, this null finding holds even when accounting for geographic exposure to environmental harm, revealing that poverty does not predict galamsey opposition more strongly among rural respondents who may be more directly vulnerable to illegal mining’s consequences. The results are therefore not strong evidence for or against the hypothesis but are consistently null across these model specifications, which constitutes as informative evidence that individual-level economic hardship is not a primary driver of galamsey attitudes in Ghana.</p>
<p>Anti-galamsey campaigns and policy interventions that target economically vulnerable individuals on the assumption that poverty drives tolerance for illegal mining may be misallocating resources. Future research could provide stronger evidence by using larger nationally representative samples with sufficient statistical power and employing other methods through which galamsey support is formed. Using community level data over individual data, such as community economic dependence on mining should be incorporated as well, given galamsey is fundamentally a community phenomenon. Lastly, using a better proxy for environmental concern in the regression analysis that better expresses concern rather than awareness would strengthen the analysis. These would works toward building a fuller understanding of what drives galamsey support and its trade-offs, and how public attitudes can be shifted in ways that support sustainable and legal approaches to natural resource governance in Ghana.</p>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-afrobarometer_r7" class="csl-entry" role="listitem">
Afrobarometer. 2018. <span>“Afrobarometer Round 7 Ghana Survey Data.”</span> <a href="https://www.afrobarometer.org/online-data-analysis/">https://www.afrobarometer.org/online-data-analysis/</a>.
</div>
<div id="ref-awewomom2024" class="csl-entry" role="listitem">
Awewomom, Jonathan, Benyade K. Benjamin, Fobi E. Osei, David Azanu, Francis Opoku, Lyndon N. Sackey, and Osei Akoto. 2024. <span>“A Review of Heath Hazards Associated with Exposure to Galamsey-Related Pollutants.”</span> <a href="https://journals.ug.edu.gh/index.php/hsij/article/view/2534/1577">https://journals.ug.edu.gh/index.php/hsij/article/view/2534/1577</a>.
</div>
<div id="ref-conroy2014" class="csl-entry" role="listitem">
Conroy, Stephen E., and Tisha L. N. Emerson. 2014. <span>“A Tale of Trade-Offs: The Impact of Macroeconomic Factors on Environmental Concern.”</span> <a href="https://www.sciencedirect.com/science/article/pii/S0301479714002898?via%3Dihub">https://www.sciencedirect.com/science/article/pii/S0301479714002898?via%3Dihub</a>.
</div>
<div id="ref-fairbrother2012" class="csl-entry" role="listitem">
Fairbrother, Malcolm. 2012. <span>“Rich People, Poor People, and Environmental Concern: Evidence Across Nations and Time.”</span> <a href="https://doi.org/10.1093/esr/jcs068">https://doi.org/10.1093/esr/jcs068</a>.
</div>
<div id="ref-Franzen2010" class="csl-entry" role="listitem">
Franzen, Axel, and Reto Meyer. 2009. <span>“Environmental Attitudes in Cross-National Perspective: A Multilevel Analysis of the ISSP 1993 and 2000.”</span> <a href="https://academic.oup.com/esr/article/26/2/219/474760?guestAccessKey=">https://academic.oup.com/esr/article/26/2/219/474760?guestAccessKey=</a>.
</div>
<div id="ref-gyimah2019" class="csl-entry" role="listitem">
Gyimah, Nathaniel. 2019. <span>“Impact of Galamsey Operations on Agricultural Land and Livelihood of Farmers: A Case Study of Affiena Community in Wassa Amenfi West District of Western Region, Ghana.”</span> <a href="https://papers.ssrn.com/sol3/Papers.cfm?abstract_id=3421765">https://papers.ssrn.com/sol3/Papers.cfm?abstract_id=3421765</a>.
</div>
<div id="ref-tougas2021global" class="csl-entry" role="listitem">
Tougas, Renee K, and Adeela Arshad-Ayaz. 2021. <span>“Global Warming and the Disproportionate Impacts of Climate Change on the Global South.”</span> PhD thesis, MA thesis in Educational Studies]. Concordia University.
</div>
<div id="ref-vovobu2024" class="csl-entry" role="listitem">
Vovobu, Augustine. 2024. <span>“Investigating the Gaps Between Ghana’s Minerals and Mining Act and the Persistence of Illegal Small-Scale Mining (Galamsey).”</span> <a href="https://www.grin.com/document/1585209#:~:text=Investigating%20the%20gaps%20between%20Ghana's%20Minerals%20and,issue%20with%20complex%20economic%20and%20environmental%20implications.">https://www.grin.com/document/1585209#:~:text=Investigating%20the%20gaps%20between%20Ghana's%20Minerals%20and,issue%20with%20complex%20economic%20and%20environmental%20implications.</a>
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>